spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password: htpw bddf yivr rkhy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true
